apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ip-address-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.11.240-192.168.11.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advertisement
  namespace: metallb-system
spec:
  # if no ipAddressPools is specified, this is associeted with all IPAddressPool available
  ipAddressPools:
  - ip-address-pool
  interfaces:
  - wlan0

