apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nginx-virtual-service 
spec:
  hosts:
  - "nginx.chemimotty.com"
  gateways:
  - istio-system/gateway
  http:
  - route:
    - destination:
        host: nginx-service
        port:
          number: 80
