apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
spec:
  istio_namespace: istio-system
  deployment:
    namespace: monitoring
  auth:
    strategy: anonymous
  external_services:
    prometheus:
      url: http://prometheus-k8s.monitoring.svc.cluster.local:9090
    tracing:
      enabled: true
      in_cluster_url: 'http://all-in-one-jaeger-query.monitoring.svc.cluster.local:16685'
      use_grpc: true
      url: 'https://jaeger.chemimotty.com'
