apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: prometheus-virtual-service
  namespace: monitoring
spec:
  hosts:
  - "prometheus.chemimotty.com"
  gateways:
  - istio-system/gateway
  http:
  - route:
    - destination:
        host: prometheus-k8s
        port:
          number: 9090
