apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus
  labels:
    name: prometheus
spec:
  selector:
    matchLabels:
      scraped-by-prometheus: "true"
  namespaceSelector:
    any: true
  endpoints:
    - port: metrics
      path: /metrics
