apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: prometheus-service
  namespace: default
spec:
  hosts:
  - "prometheus.chemimotty.com"
  gateways:
  - istio-system/my-gateway
  http:
  - route:
    - destination:
        host: prometheus-operated
        port:
          number: 9090
