apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: jaeger-service
spec:
  hosts:
  - "jaeger.chemimotty.com"
  gateways:
  - istio-system/gateway
  http:
  - route:
    - destination:
        host: all-in-one-jaeger-query
        port:
          number: 16686
