apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# helm template \                                                                                                                                                                                                                                                      130 ↵
#   --namespace istio-system \
#   --set auth.strategy="anonymous" \
#   --repo https://kiali.org/helm-charts \
#   kiali-server \
#   kiali-server --version 1.66.0 > kiali-v1.66.0.yaml
- kiali-v1.66.0.yaml
- virtual-service.yaml

