apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istiocontrolplane
  namespace: istio-system
spec:
  profile: default
  meshConfig:
    defaultConfig:
      tracing:
        sampling: 100.0 # 100% sampling rate
        zipkin:
          address: all-in-one-jaeger-collector.monitoring.svc.cluster.local:9411
