apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: istio-system

resources:
# bundle is large and `kubectl apply` gets error, so use `kubectl create`
# wget https://github.com/prometheus-operator/prometheus-operator/releases/download/v0.66.0/bundle.yaml 
- bundle.yaml
- rbac.yaml
- prometheus.yaml
- virtual-service.yaml
- istio-monitor.yaml

