apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
spec:
  istio_namespace: istio-system
  deployment:
    namespace: istio-system
  auth:
    strategy: anonymous
  external_services:
    prometheus:
      url: http://prometheus-operated.istio-system.svc.cluster.local:9090
