apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: elastic-system

resources:
# modify namespace with label `istio-injection: enabled`
- operator.yaml
- persistentvolume.yaml
