apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  # labels:
  #   type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs: 
    path: /nfs/shared
    server: 192.168.11.4
