apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-system-cert
  namespace: istio-system
spec:
  secretName: istio-system-cert-tls
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  dnsNames:
  - prometheus.chemimotty.com
  - nginx.chemimotty.com
  - grafana.chemimotty.com
  - jaeger.chemimotty.com
  - kiali.chemimotty.com
